apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80 
  type: ClusterIP  

