apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops2
  name: giropops2
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"  
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"  
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: nginx
    name: nginx    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
