apiVersion: v1
kind: Pod
metadata:
  name: "privado"
  namespace: default
  labels:
    app: "privado"
spec:
  containers:
  - name: privado
    image: rodrigo2186/meu_apache:1.0.0
  imagePullSecrets:
  - name: docker-hub

